### PR TITLE
support for wasi_snapshot_preview1 of wasi sdk 11

### PR DESCRIPTION
**Pull request by pmp-p**
hi, btw where is the source code of polyfill.wasm ?

### CODE REVIEW

**Comment by sunfishcode** [comment]
The original polyfill was a demo, and the code can be found in an old branch, here:

https://github.com/bytecodealliance/wasmtime/tree/polyfill/wasmtime-wasi

It was formed by compiling Wasmtime's initial WASI implementation, written in C, using Emscripten. Wasmtime itself has since moved to an implementation written in Rust and dropped the C version. And while the Rust version could theoretically be ported to Rust's wasm32-unknown-emscripten target in the same way, this hasn't been done yet.

Compiling C or Rust WASI implementations to JS with Emscripten tends to produce a lot more code than is really needed. For practical purposes, the following hand-written polyfills aren't complete, but may be more practical:

https://github.com/bjorn3/rust/blob/compile_rustc_wasm4/rustc.html

https://github.com/WebAssembly/waterfall/blob/master/src/wasi.js

**Comment by pmp-p** [comment]
@sunfishcode , thanks a lot for details and the the pointers !  i was trying indeed to hand write a "smallest" polyfill but i was struggling with clock_time_get / gettimeofday and wanted to know how wasi.dev has done it.

**Comment by sunfishcode** [comment]
In the Emscripten-compiled version, `clock_time_get` either calls `Date.now()` in JS, or it does this: https://github.com/emscripten-core/emscripten/blob/9456db2b95771f0d85de4b78cc0beeeb4848dd6e/src/library.js#L2925.

**Comment by sunfishcode** [comment]
Closing, as the old polyfill is no longer maintained. If you're interested in a small polyfill, [this project](git@github.com:sunfishcode/wasi.dev.git) is a smaller approach due to being hand-written in JS.

**Pull request closed without merging**
