### PR TITLE
Use system theme by default

### PR DESCRIPTION
**Pull request by rajsite**
Update the docusaurus theme to [respectPrefersColorScheme](https://docusaurus.io/docs/api/themes/configuration#color-mode---dark-mode) by default. Protect my eyes 🔦😎

### CODE REVIEW

**Comment by rajsite** [comment]
Doesn't look like owners are defined for reviews so just in case, FYI @ericgregory

**Review by ericgregory — APPROVED** [review]

**Comment by rajsite** [comment]
Thanks @ericgregory! Appreciate you taking the time to give it a look! :)

**Comment by rajsite** [comment]
Does look the [deploy to GitHub pages failed](https://github.com/bytecodealliance/wasi.dev/actions/runs/10647010282/job/29514493320).  The docusaurus build passed so probably unrelated to this change.

**Comment by ericgregory** [comment]
> Does look the [deploy to GitHub pages failed](https://github.com/bytecodealliance/wasi.dev/actions/runs/10647010282/job/29514493320). The docusaurus build passed so probably unrelated to this change.

Thanks for the contribution! That deploy fail is definitely unrelated to this change. We're in the process of getting GitHub Actions properly configured -- hope to have that sorted soon, but we'll do a manual build in the meantime.

**Pull request merged**
